#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="olefy"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Olefy"
set -a
source ${CONFIG_PATH}${CONFIG_FILE}
silent exec python3 /usr/local/bin/olefy.py
